version: 2.1

alias:
  - &install-sbt
    name: Install sbt
    command: |
      echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list && \
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
      sudo apt update && \
      sudo apt install sbt -y

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: *install-sbt
      - checkout
      - restore_cache:
          keys:
            - sbt-cache-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/Dependencies.scala" }}
            - sbt-cache
      - run:
          name: Fetch compile dependencies
          command: sbt update
      - run:
          name: Compile
          command: sbt compile
      - run:
          name: Fetch test dependencies
          command: sbt test:update
      - run:
          name: Run unit tests
          command: sbt test
      - save_cache:
          key: sbt-cache-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/Dependencies.scala" }}
          paths:
            - ~/.sbt
            - ~/.cache/coursier

orbs:
  slack: circleci/slack@3

workflows:
  version: 2

  $name;format="normalize"$:
    jobs:
      - build-and-test:
          post-steps:
            - slack/status
