version: 2.1

alias:
  - &install-sbt
    name: Install sbt
    command: |
      echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list && \
      echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list && \
      curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add && \
      sudo apt update && \
      sudo apt install sbt

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: *install-sbt
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Create a new sbt project from the g8 template
          command: sbt g8
      - run:
          name: Run the test suite of the newly created project
          command: cd target/g8 && sbt clean test
      - save_cache:
          key: sbt-cache
          paths:
            - ~/.sbt
            - ~/.cache/coursier

orbs:
  slack: circleci/slack@3

workflows:
  version: 2

  scala-seed:
    jobs:
      - build-and-test:
          post-steps:
            - slack/status


