name: Scala Seed Build Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: scala-seed-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/Dependencies.scala') }}
          path: |
            ~/.sbt
            ~/.cache/coursier
          restore-keys: |
            scala-seed-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}
            scala-seed-${{ hashFiles('**/build.properties') }}
            scala-seed

      - name: Create new sbt project from g8 template
        run: sbt g8

      - name: Execute test suite
        run: cd target/g8 && sbt clean test